### ISSUE TITLE
Add delay

### ISSUE THREAD

**Issue by chasturansky** [flozz/StackBlur#22] opened 2017-11-21 20:49 UTC
Is it possible to add in a delay to the image capture. So if you have animations you will not capture whitespace.

**Comment by flozz** [comment] 2017-11-22 07:54
Hello,

I do not understand what your whant to do. Have you an example to show me what you are trying to and what is the problem?

**Comment by chasturansky** [comment] 2017-11-22 17:30
Here are a few screenshots in example one the page loads perfectly there's a blur where it needs to be. In example 2 I added an animation to the image so it takes half a second to animation with a delay of one second, but the blur does not appear. 
<img width="1392" alt="example 2" src="https://user-images.githubusercontent.com/15337851/33141333-b30ceeb8-cf67-11e7-949c-a1821f680674.png">
<img width="1392" alt="example 1" src="https://user-images.githubusercontent.com/15337851/33141334-b3239fe6-cf67-11e7-960a-5fe65a99780b.png">

**Comment by chasturansky** [comment] 2017-11-22 17:35
Here's the repo https://github.com/chasturansky/blur

**Comment by flozz** [comment] 2017-11-22 20:13
Your issue is not related to StackBlur. The problem is: when you take a "screenshot" of the page using html2canvas, the image is no visible so the canvas is blank, and then you blur the white canvas (so there is nothing visible).

There is several trick possible to fix that, I modified your HTML file to make a working effect by using a white div over the page:

https://pastebin.com/xKmpwm8i

**Comment by flozz** [comment] 2017-11-24 14:05
I close this issue as it is not an issue in StackBlur, but don't hesitate to ask if you have further questions

**Closed by flozz** 2017-11-24 14:05 UTC

**Comment by chasturansky** [comment] 2017-11-24 17:38
Thanks! Your suggestions did help.
