### ISSUE TITLE
Splitting the blurring between different WebWorkers renders black bands in the drawing

### ISSUE THREAD

**Issue by MeerKatDev** [flozz/StackBlur#12] opened 2016-10-01 09:26 UTC
As in the title. Dividing the blurring work between four webworkers, I get this:
![catturablur](https://cloud.githubusercontent.com/assets/1340996/19013183/d660367c-87c9-11e6-910d-7661b9f33fcc.PNG)

**Comment by flozz** [comment] 2016-10-03 10:42
Hello,

Can you give me some code to reproduce?

**Comment by amilajack** [comment] 2016-10-29 04:41
Should this be closed?

**Comment by brettz9** [comment] 2020-04-04 03:18
Am closing due to no reproducible test case. Feel free to (re)open if one can be found. Thanks!

**Closed by brettz9** 2020-04-04 03:18 UTC
